### ISSUE TITLE
Pages needed

### ISSUE THREAD

**Issue by mhwilkes** [mhwilkes/pod-1.2.0-dangerous-ducks-hackathon#5]
Let's get a preliminary List of pages that we want to create and are needed to fully utilize our WebRTC Feature.

Keep it to probably just 1 page that then leads to your individual meeting page

My thoughts:

- Home / Start Meeting
- Token based Meeting Page

**Comment by kobeeraveendran** [comment]
Yeah that seems fine by me (if we're opting to go the route of speakeasy). On Speakeasy there's only the landing page where the group is created then the video screen (not sure if we're going to need much of the meeting config stuff for this one).

**Comment by mhwilkes** [comment]
I think our best bet is to keep it simple. Im really into the idea of it being as simple as anonymous person starts room with uuid or token to differentiate it, and that token is then used as a link to that one off room. 

Keeping it simple if we go with the elderly spin or we could spin it into impromptu socially distanced dates or conversations or talking to people.

Keeping the barrier of entry as low as possible would be the best

**Comment by mhwilkes** [comment]
Marking as resolved
